import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { Providers } from "@/lib/providers";
import { config } from "@/lib/wagmi";
import { cn } from "@repo/ui/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { headers } from "next/headers";
import { Toaster } from "sonner";
import { cookieToInitialState } from "wagmi";

export const metadata: Metadata = {
  title: "Neonix Labs",
  description: "Generated by Neonix Labs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body
        className={cn(
          `${GeistSans.variable} ${GeistMono.variable}`,
          "bg-[#0C0C0C] overflow-x-hidden dark antialiased relative",
        )}
      >
        <div className="dotted-bg absolute w-screen h-full top-0" />

        <Providers initialState={initialState}>
          <div className="px-4 sm:px-0 overflow-hidden md:overflow-visible">
            <Header />

            {children}

            <Footer />
          </div>
        </Providers>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
