import type { Metadata } from 'next'
import '@repo/ui/globals.css'
import Link from 'next/link'
import { cn } from '@repo/ui/utils'
import { MountainIcon } from '@/components/mountain-icon'
import { Toaster } from 'sonner'
import { Providers } from '@/lib/providers'
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import { config } from '@/lib/wagmi'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

export const metadata: Metadata = {
  title: 'Neonix Labs',
  description: 'Generated by Neonix Labs',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body
        className={cn(
          `${GeistSans.variable} ${GeistMono.variable}`,
          'whitespace-pre-line overscroll-none relative isolate bg-gray-900 text-white',
        )}
      >
        <div className="absolute inset-y-0 -z-10 w-full overflow-hidden ring-1 ring-white/5">
          <svg
            aria-hidden="true"
            className="absolute inset-0 h-full w-full stroke-gray-700 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]"
          >
            <defs>
              <pattern
                x="100%"
                y={-1}
                id="54f88622-e7f8-4f1d-aaf9-c2f5e46dd1f2"
                width={200}
                height={200}
                patternUnits="userSpaceOnUse"
              >
                <path d="M130 200V.5M.5 .5H200" fill="none" />
              </pattern>
            </defs>
            <svg x="100%" y={-1} className="overflow-visible fill-gray-800/20">
              <path d="M-470.5 0h201v201h-201Z" strokeWidth={0} />
            </svg>
            <rect
              fill="url(#54f88622-e7f8-4f1d-aaf9-c2f5e46dd1f2)"
              width="100%"
              height="100%"
              strokeWidth={0}
            />
          </svg>
          <div
            aria-hidden="true"
            className="absolute -left-56 top-[calc(100%-13rem)] transform-gpu blur-3xl lg:left-[max(-14rem,calc(100%-59rem))] lg:top-[calc(50%-7rem)]"
          >
            <div
              style={{
                clipPath:
                  'polygon(74.1% 56.1%, 100% 38.6%, 97.5% 73.3%, 85.5% 100%, 80.7% 98.2%, 72.5% 67.7%, 60.2% 37.8%, 52.4% 32.2%, 47.5% 41.9%, 45.2% 65.8%, 27.5% 23.5%, 0.1% 35.4%, 17.9% 0.1%, 27.6% 23.5%, 76.1% 2.6%, 74.1% 56.1%)',
              }}
              className="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-br from-[#80caff] to-[#4f46e5] opacity-20"
            />
          </div>
        </div>

        <Providers initialState={initialState}>
          <div className="flex flex-col min-h-dvh font-inter mx-auto px-4 sm:px-0">
            <Header />

            {children}

            <Footer />
          </div>
        </Providers>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  )
}

function Header() {
  return (
    <div className="p-4 container w-full mx-auto h-[72px]">
      <header className="flex items-center">
        <Link
          href="/"
          className="flex items-center justify-center gap-2"
          prefetch={false}
        >
          <MountainIcon className="size-8" />
          <span className="sr-only">Neonix Labs</span>
        </Link>
        <nav className="ml-auto gap-4 sm:gap-6 flex items-center">
          {/* <div className="relative">
            <span className="animate-pulse h-4 w-4 bg-blue-500 rounded-full inline-block absolute -right-1 -top-1"></span>
            <Link
              href="/recap"
              className={buttonVariants({
                variant: 'secondary',
              })}
            >
              Recap
            </Link>
          </div> */}

          <Link
            href="/about"
            className="text-sm font-semibold leading-6 text-white hover:underline transition-colors duration-200 hover:text-gray-100"
          >
            About
          </Link>
          <Link
            href="/contact"
            className="text-sm font-semibold leading-6 text-white hover:underline transition-colors duration-200 hover:text-gray-100"
          >
            Contact
          </Link>
        </nav>
      </header>
    </div>
  )
}

function Footer() {
  return (
    <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 container mx-auto">
      <p className="text-xs text-muted-foreground">
        &copy; 2024 Neonix Labs. All rights reserved.
      </p>
    </footer>
  )
}
